train_indices : []
num_workers: 16
num_epochs: 100
batch_size: 4
lr: 0.001
weight_decay: 0.0001
sched: 
    update_interval: "epoch"
    update_freq: 1
    MultiStepLR:
        milestones: [50] 
        gamma: 0.1
